window.TASKS = [
  {
    id: 'svg-chess-knight',
    title: 'SVG шахматный конь',
    tags: ['геометрия', 'svg', 'иконка'],
    prompt: 'Нарисуй фигурку шахматного коня в SVG: чистый, узнаваемый, эстетичный векторный силуэт; аккуратные кривые Безье; без растровых вставок. Самодостаточный HTML с инлайн-SVG. Тёмный фон, фигура крупная, по центру, хорошо читается; уместны тонкие детали (грива, глаз, лёгкий объём через градиент/тень), но без китча.',
    solutions: [
      { model: 'Claude Opus 4.8', slug: 'opus-4.8', dir: 'demos/svg-chess-knight/opus-4.8/' },
      { model: 'GPT-5.5 Codex', slug: 'gpt-5.5-codex', dir: 'demos/svg-chess-knight/gpt-5.5-codex/' },
      { model: 'Claude Fable 5', slug: 'fable-5', dir: 'demos/svg-chess-knight/fable-5/' },
      { model: 'Claude Sonnet 5', slug: 'sonnet-5', dir: 'demos/svg-chess-knight/sonnet-5/' },
      { model: 'GPT-5.6 Sol', slug: 'gpt-5.6-sol', dir: 'demos/svg-chess-knight/gpt-5.6-sol/' },
      { model: 'GPT-5.6 Luna', slug: 'gpt-5.6-luna', dir: 'demos/svg-chess-knight/gpt-5.6-luna/' },
    ],
  },
  {
    id: 'solar-system',
    title: 'Солнечная система',
    tags: ['космос', '3D', 'орбиты'],
    prompt: 'Солнечная система на canvas без библиотек: Солнце и планеты на эллиптических орбитах с правдоподобными относительными размерами орбит, наклонами и скоростями, кольца Сатурна, несколько крупных лун, освещение планет от Солнца с ночной стороной, затухающие орбитальные следы. Трёхмерный вид с медленным вращением камеры, масштаб настраивается. Планка: добивайся максимально кинематографичной, насыщенной и достоверной картинки в реальном времени; конкретные технические приёмы выбираешь сам — оценивается художественное качество и живость, а не следование рецепту.',
    solutions: [
      { model: 'Claude Opus 4.8', slug: 'opus-4.8', dir: 'demos/solar-system/opus-4.8/' },
      { model: 'GPT-5.5 Codex', slug: 'gpt-5.5-codex', dir: 'demos/solar-system/gpt-5.5-codex/' },
      { model: 'Claude Fable 5', slug: 'fable-5', dir: 'demos/solar-system/fable-5/' },
      { model: 'Claude Sonnet 5', slug: 'sonnet-5', dir: 'demos/solar-system/sonnet-5/' },
      { model: 'GPT-5.6 Sol', slug: 'gpt-5.6-sol', dir: 'demos/solar-system/gpt-5.6-sol/' },
    ],
  },
  {
    id: 'mandelbrot',
    title: 'Фрактал Мандельброта',
    tags: ['математика', 'пиксели', 'масштаб'],
    prompt: 'Отрисуй множество Мандельброта на HTML5 canvas с плавной (continuous/smooth) раскраской. Сделай интерактив: зум колесом мыши с центрированием на курсоре и панорамирование перетаскиванием, с пересчётом при изменении. Глубина итераций должна расти с увеличением зума. Красивая палитра. Покажи текущий зум/координаты.',
    solutions: [
      { model: 'Claude Opus 4.8', slug: 'opus-4.8', dir: 'demos/mandelbrot/opus-4.8/' },
      { model: 'GPT-5.5 Codex', slug: 'gpt-5.5-codex', dir: 'demos/mandelbrot/gpt-5.5-codex/' },
      { model: 'Claude Fable 5', slug: 'fable-5', dir: 'demos/mandelbrot/fable-5/' },
      { model: 'Claude Sonnet 5', slug: 'sonnet-5', dir: 'demos/mandelbrot/sonnet-5/' },
      { model: 'GPT-5.6 Sol', slug: 'gpt-5.6-sol', dir: 'demos/mandelbrot/gpt-5.6-sol/' },
    ],
  },
  {
    id: 'lorenz',
    title: 'Система Лоренца',
    tags: ['аттрактор', '3D', 'траектория'],
    prompt: 'Визуализируй аттрактор Лоренца: численное интегрирование классических уравнений (σ=10, ρ=28, β=8/3), 3D-траектория с медленным автоматическим вращением камеры и затухающим следом, на canvas, в реальном времени. Красивый градиент цвета вдоль траектории.',
    solutions: [
      { model: 'Claude Opus 4.8', slug: 'opus-4.8', dir: 'demos/lorenz/opus-4.8/' },
      { model: 'GPT-5.5 Codex', slug: 'gpt-5.5-codex', dir: 'demos/lorenz/gpt-5.5-codex/' },
      { model: 'Claude Fable 5', slug: 'fable-5', dir: 'demos/lorenz/fable-5/' },
      { model: 'Claude Sonnet 5', slug: 'sonnet-5', dir: 'demos/lorenz/sonnet-5/' },
      { model: 'GPT-5.6 Sol', slug: 'gpt-5.6-sol', dir: 'demos/lorenz/gpt-5.6-sol/' },
    ],
  },
  {
    id: 'boids',
    title: 'Стая boids',
    tags: ['эмерджентность', 'агенты', 'canvas'],
    prompt: 'Смоделируй стаю птиц (boids) на canvas: правила разделения, выравнивания и сцепления; не менее 400 агентов в реальном времени с плавным движением. Ползунки силы каждого из трёх правил, радиуса восприятия и максимальной скорости. Мир тороидальный (агенты переходят через края). Подсвети одного агента, его радиус восприятия и соседей, которых он видит.',
    solutions: [
      { model: 'Claude Opus 4.8', slug: 'opus-4.8', dir: 'demos/boids/opus-4.8/' },
      { model: 'GPT-5.5 Codex', slug: 'gpt-5.5-codex', dir: 'demos/boids/gpt-5.5-codex/' },
      { model: 'Claude Fable 5', slug: 'fable-5', dir: 'demos/boids/fable-5/' },
      { model: 'Claude Sonnet 5', slug: 'sonnet-5', dir: 'demos/boids/sonnet-5/' },
      { model: 'GPT-5.6 Sol', slug: 'gpt-5.6-sol', dir: 'demos/boids/gpt-5.6-sol/' },
    ],
  },
  {
    id: 'verlet-cloth',
    title: 'Ткань (верлет)',
    tags: ['физика', 'верлет', 'интерактив'],
    prompt: 'Симуляция ткани на верлет-интегрировании: сетка частиц со связями-констрейнтами, верхний край закреплён в нескольких точках, гравитация и лёгкий переменный ветер. Мышью можно схватить и тянуть ткань; при сильном растяжении связи рвутся. Кнопка сброса. Отрисовка сетки на canvas в реальном времени.',
    solutions: [
      { model: 'Claude Opus 4.8', slug: 'opus-4.8', dir: 'demos/verlet-cloth/opus-4.8/' },
      { model: 'GPT-5.5 Codex', slug: 'gpt-5.5-codex', dir: 'demos/verlet-cloth/gpt-5.5-codex/' },
      { model: 'Claude Fable 5', slug: 'fable-5', dir: 'demos/verlet-cloth/fable-5/' },
      { model: 'Claude Sonnet 5', slug: 'sonnet-5', dir: 'demos/verlet-cloth/sonnet-5/' },
      { model: 'GPT-5.6 Sol', slug: 'gpt-5.6-sol', dir: 'demos/verlet-cloth/gpt-5.6-sol/' },
    ],
  },
  {
    id: 'falling-sand',
    title: 'Падающий песок',
    tags: ['клеточный автомат', 'пиксели', 'интерактив'],
    prompt: 'Сделай «падающий песок» — клеточный автомат на canvas. Вещества: песок (сыплется, образует горки, тонет в воде), вода (падает и растекается), камень (неподвижен), дерево (горит), огонь (поджигает дерево, гаснет дымом), дым (поднимается и тает). Кисть мышью с выбором вещества и размера, пауза и очистка. Симуляция должна быть честной: без телепортаций и явной асимметрии влево/вправо.',
    solutions: [
      { model: 'Claude Opus 4.8', slug: 'opus-4.8', dir: 'demos/falling-sand/opus-4.8/' },
      { model: 'GPT-5.5 Codex', slug: 'gpt-5.5-codex', dir: 'demos/falling-sand/gpt-5.5-codex/' },
      { model: 'Claude Fable 5', slug: 'fable-5', dir: 'demos/falling-sand/fable-5/' },
      { model: 'Claude Sonnet 5', slug: 'sonnet-5', dir: 'demos/falling-sand/sonnet-5/' },
      { model: 'GPT-5.6 Sol', slug: 'gpt-5.6-sol', dir: 'demos/falling-sand/gpt-5.6-sol/' },
    ],
  },
  {
    id: 'raycaster-maze',
    title: 'Рейкастер-лабиринт',
    tags: ['псевдо-3D', 'алгоритмы', 'игра'],
    prompt: 'Псевдо-3D лабиринт в стиле Wolfenstein 3D на canvas, без библиотек: процедурно сгенерированный связный лабиринт, рейкастинг по сетке (DDA), корректная перспектива без эффекта «рыбьего глаза», стены с разной яркостью по стороне и затемнением по дальности, пол и потолок, мини-карта с положением игрока и сектором обзора. Управление: W/S — вперёд/назад, A/D — стрейф, стрелки ←/→ — поворот; коллизии со стенами со скольжением.',
    solutions: [
      { model: 'Claude Opus 4.8', slug: 'opus-4.8', dir: 'demos/raycaster-maze/opus-4.8/' },
      { model: 'GPT-5.5 Codex', slug: 'gpt-5.5-codex', dir: 'demos/raycaster-maze/gpt-5.5-codex/' },
      { model: 'Claude Fable 5', slug: 'fable-5', dir: 'demos/raycaster-maze/fable-5/' },
      { model: 'Claude Sonnet 5', slug: 'sonnet-5', dir: 'demos/raycaster-maze/sonnet-5/' },
      { model: 'GPT-5.6 Sol', slug: 'gpt-5.6-sol', dir: 'demos/raycaster-maze/gpt-5.6-sol/' },
    ],
  },
  {
    id: 'light-2d',
    title: '2D-свет и тени',
    tags: ['геометрия', 'свет', 'canvas'],
    prompt: 'Источник света в 2D, следующий за курсором, и набор многоугольников-препятствий. Построй геометрически точный полигон видимости: лучи к вершинам препятствий (с малыми угловыми смещениями), пересечения луч-отрезок, сортировка по углу. Освещённую область залей радиальным градиентом, добавь мягкое свечение вокруг источника. Чекбокс отладочного режима — показать лучи и вершины.',
    solutions: [
      { model: 'Claude Opus 4.8', slug: 'opus-4.8', dir: 'demos/light-2d/opus-4.8/' },
      { model: 'GPT-5.5 Codex', slug: 'gpt-5.5-codex', dir: 'demos/light-2d/gpt-5.5-codex/' },
      { model: 'Claude Fable 5', slug: 'fable-5', dir: 'demos/light-2d/fable-5/' },
      { model: 'Claude Sonnet 5', slug: 'sonnet-5', dir: 'demos/light-2d/sonnet-5/' },
      { model: 'GPT-5.6 Sol', slug: 'gpt-5.6-sol', dir: 'demos/light-2d/gpt-5.6-sol/' },
    ],
  },
  {
    id: 'procedural-walker',
    title: 'Идущий человечек',
    tags: ['анимация', 'кинематика', 'canvas'],
    prompt: 'Процедурная анимация идущего человечка (stick figure) на canvas без покадровых спрайтов: цикл походки с фазами опоры и переноса, сгиб коленей через обратную кинематику, движение рук в противофазе ногам, вертикальное покачивание и наклон корпуса. Земля движется, создавая иллюзию ходьбы; стопы в фазе опоры не должны скользить относительно земли. Ползунок скорости от медленной ходьбы до бега с плавной сменой характера походки.',
    solutions: [
      { model: 'Claude Opus 4.8', slug: 'opus-4.8', dir: 'demos/procedural-walker/opus-4.8/' },
      { model: 'GPT-5.5 Codex', slug: 'gpt-5.5-codex', dir: 'demos/procedural-walker/gpt-5.5-codex/' },
      { model: 'Claude Fable 5', slug: 'fable-5', dir: 'demos/procedural-walker/fable-5/' },
      { model: 'Claude Sonnet 5', slug: 'sonnet-5', dir: 'demos/procedural-walker/sonnet-5/' },
      { model: 'GPT-5.6 Sol', slug: 'gpt-5.6-sol', dir: 'demos/procedural-walker/gpt-5.6-sol/' },
    ],
  },
  {
    id: 'svg-bicycle',
    title: 'SVG велосипед',
    tags: ['геометрия', 'svg', 'устройство мира'],
    prompt: 'Нарисуй классический велосипед в SVG: технически правдоподобная конструкция — ромбовидная рама из двух замкнутых треугольников, рулевая труба с вилкой к оси переднего колеса, подседельная труба к каретке, цепь от ведущей звезды с шатунами и педалями к задней звёздочке на оси заднего колеса, спицы, седло, руль, тормоза. Самодостаточный HTML с инлайн-SVG, чистый векторный стиль, светлая фигура на тёмном фоне, без растровых вставок.',
    solutions: [
      { model: 'Claude Opus 4.8', slug: 'opus-4.8', dir: 'demos/svg-bicycle/opus-4.8/' },
      { model: 'GPT-5.5 Codex', slug: 'gpt-5.5-codex', dir: 'demos/svg-bicycle/gpt-5.5-codex/' },
      { model: 'Claude Fable 5', slug: 'fable-5', dir: 'demos/svg-bicycle/fable-5/' },
      { model: 'Claude Sonnet 5', slug: 'sonnet-5', dir: 'demos/svg-bicycle/sonnet-5/' },
      { model: 'GPT-5.6 Sol', slug: 'gpt-5.6-sol', dir: 'demos/svg-bicycle/gpt-5.6-sol/' },
    ],
  },
  {
    id: 'double-pendulum',
    title: 'Двойной маятник',
    tags: ['физика', 'canvas', 'хаос'],
    prompt: 'Отобрази в HTML5 физику двойного маятника: два стержня, два точечных груза на шарнирах, корректные уравнения движения и численное интегрирование, реальное время. Добавь затухающий след нижнего груза, управление пуском/паузой и сбросом, ползунки масс и длин, и режим «призрак» с крошечным отклонением начального угла для демонстрации чувствительности к начальным условиям (хаос).',
    solutions: [
      { model: 'Claude Opus 4.8', slug: 'opus-4.8', dir: 'demos/double-pendulum/opus-4.8/' },
      { model: 'GPT-5.5 Codex', slug: 'gpt-5.5-codex', dir: 'demos/double-pendulum/gpt-5.5-codex/' },
      { model: 'Claude Fable 5', slug: 'fable-5', dir: 'demos/double-pendulum/fable-5/' },
      { model: 'Claude Sonnet 5', slug: 'sonnet-5', dir: 'demos/double-pendulum/sonnet-5/' },
      { model: 'GPT-5.6 Sol', slug: 'gpt-5.6-sol', dir: 'demos/double-pendulum/gpt-5.6-sol/' },
    ],
  },
  {
    id: 'css-newspaper',
    title: 'Газетная полоса',
    tags: ['типографика', 'вёрстка', 'CSS'],
    prompt: 'Сверстай первую полосу газеты чистым HTML/CSS, без единой строки JavaScript: шапка с названием издания, датой и номером выпуска; главная статья с крупным заголовком, подзаголовком, лидом и буквицей; вёрстка в несколько колонок с выключкой по ширине и переносами; врезка с цитатой; фото-плейсхолдеры с подписями; линейки между материалами; колонтитул. Газетная типографика с серифными шрифтами, аккуратные интервалы. Русский язык, правдоподобные тексты.',
    solutions: [
      { model: 'Claude Opus 4.8', slug: 'opus-4.8', dir: 'demos/css-newspaper/opus-4.8/' },
      { model: 'GPT-5.5 Codex', slug: 'gpt-5.5-codex', dir: 'demos/css-newspaper/gpt-5.5-codex/' },
      { model: 'Claude Fable 5', slug: 'fable-5', dir: 'demos/css-newspaper/fable-5/' },
      { model: 'Claude Sonnet 5', slug: 'sonnet-5', dir: 'demos/css-newspaper/sonnet-5/' },
      { model: 'GPT-5.6 Sol', slug: 'gpt-5.6-sol', dir: 'demos/css-newspaper/gpt-5.6-sol/' },
    ],
  },

  // ── Технические 3D-задачи (ось «корректность конвейера») ──
  {
    id: 'solid-3d',
    title: '3D-тело (софт-рендер)',
    tags: ['3D', 'рендеринг', 'геометрия'],
    prompt: 'Софт-рендер вращающегося 3D-тела на canvas, без WebGL и без библиотек — построй мини-конвейер вручную: матрицы поворота и перспективная проекция, отсечение нелицевых граней (backface culling), сортировка граней по глубине или z-буфер, освещение от точечного источника с плоским и гладким (Гуро) затенением. Объект — выпуклый многогранник или тор с достаточным числом граней, медленное автоматическое вращение по двум осям. Переключатели каркас/заливка и плоское/гладкое затенение. Глубина корректна, без артефактов перекрытия.',
    solutions: [
      { model: 'Claude Opus 4.8', slug: 'opus-4.8', dir: 'demos/solid-3d/opus-4.8/' },
      { model: 'GPT-5.5 Codex', slug: 'gpt-5.5-codex', dir: 'demos/solid-3d/gpt-5.5-codex/' },
      { model: 'Claude Fable 5', slug: 'fable-5', dir: 'demos/solid-3d/fable-5/' },
      { model: 'Claude Sonnet 5', slug: 'sonnet-5', dir: 'demos/solid-3d/sonnet-5/' },
      { model: 'GPT-5.6 Sol', slug: 'gpt-5.6-sol', dir: 'demos/solid-3d/gpt-5.6-sol/' },
    ],
  },
  {
    id: 'surface-plot',
    title: '3D-поверхность функции',
    tags: ['математика', '3D', 'визуализация'],
    prompt: 'Построй и анимируй 3D-график функции z=f(x,y) на canvas без библиотек: сетка узлов, вычисление высоты, 3D-проекция с медленным вращением камеры. Освещение по Ламберту с нормалями в узлах, цветовая карта по высоте, сортировка полигонов по глубине (алгоритм художника) или z-буфер для верного перекрытия. Анимируй во времени волновую поверхность (например, затухающая рябь sin(r−t)/r) и дай переключение между несколькими функциями (рябь, седло, гауссиана). Каркас опционально поверх заливки.',
    solutions: [
      { model: 'Claude Opus 4.8', slug: 'opus-4.8', dir: 'demos/surface-plot/opus-4.8/' },
      { model: 'GPT-5.5 Codex', slug: 'gpt-5.5-codex', dir: 'demos/surface-plot/gpt-5.5-codex/' },
      { model: 'Claude Fable 5', slug: 'fable-5', dir: 'demos/surface-plot/fable-5/' },
      { model: 'Claude Sonnet 5', slug: 'sonnet-5', dir: 'demos/surface-plot/sonnet-5/' },
      { model: 'GPT-5.6 Sol', slug: 'gpt-5.6-sol', dir: 'demos/surface-plot/gpt-5.6-sol/' },
    ],
  },
  {
    id: 'voxel-terrain',
    title: 'Воксельный ландшафт',
    tags: ['псевдо-3D', 'ландшафт', 'алгоритмы'],
    prompt: 'Воксельный рельеф в стиле VoxelSpace/Comanche на canvas, без библиотек: процедурная карта высот на основе шума, рендер по вертикальным столбцам экрана с проекцией высоты и закраской по карте цвета, корректная перспектива, затухание в туман по дальности и градиент неба у горизонта. Камера непрерывно летит над ландшафтом; настройки высоты камеры, дальности отрисовки и линии горизонта. Плавно, в реальном времени, без 3D-библиотек.',
    solutions: [
      { model: 'Claude Opus 4.8', slug: 'opus-4.8', dir: 'demos/voxel-terrain/opus-4.8/' },
      { model: 'GPT-5.5 Codex', slug: 'gpt-5.5-codex', dir: 'demos/voxel-terrain/gpt-5.5-codex/' },
      { model: 'Claude Fable 5', slug: 'fable-5', dir: 'demos/voxel-terrain/fable-5/' },
      { model: 'Claude Sonnet 5', slug: 'sonnet-5', dir: 'demos/voxel-terrain/sonnet-5/' },
      { model: 'GPT-5.6 Sol', slug: 'gpt-5.6-sol', dir: 'demos/voxel-terrain/gpt-5.6-sol/' },
    ],
  },

  // ── Эстетические задачи (ось «вкус и достоверность»; общий «художественный хвост» только у них) ──
  {
    id: 'earth-globe',
    title: 'Вращающийся земной шар',
    tags: ['3D', 'планета', 'атмосфера'],
    prompt: 'Вращающийся земной шар на canvas без библиотек: сфера с проекцией и наложением карты суши и океана (карта процедурная или зашитая в коде, без загрузки внешних файлов), наклон оси около 23.5°, медленное вращение. Дневная и ночная стороны с мягким терминатором, атмосферное свечение по краю диска, огни городов на ночной стороне, блик солнца на океане, слой облаков и звёздное небо на фоне; источник света можно двигать. Планка: добивайся максимально кинематографичной, насыщенной и достоверной картинки в реальном времени; конкретные технические приёмы выбираешь сам — оценивается художественное качество и живость, а не следование рецепту.',
    solutions: [
      { model: 'Claude Opus 4.8', slug: 'opus-4.8', dir: 'demos/earth-globe/opus-4.8/' },
      { model: 'GPT-5.5 Codex', slug: 'gpt-5.5-codex', dir: 'demos/earth-globe/gpt-5.5-codex/' },
      { model: 'Claude Fable 5', slug: 'fable-5', dir: 'demos/earth-globe/fable-5/' },
      { model: 'Claude Sonnet 5', slug: 'sonnet-5', dir: 'demos/earth-globe/sonnet-5/' },
      { model: 'GPT-5.6 Sol', slug: 'gpt-5.6-sol', dir: 'demos/earth-globe/gpt-5.6-sol/' },
    ],
  },
  {
    id: 'particle-flow',
    title: 'Поток частиц 3D',
    tags: ['частицы', '3D', 'демосцена'],
    prompt: 'Десятки тысяч частиц, движущихся в трёхмерном поле скоростей (например, curl-noise), на canvas в реальном времени. 3D-проекция с глубиной, аддитивное свечение, цвет по скорости или глубине, лёгкая дымка и затухающие следы, плавное перетекание потоков; медленное вращение камеры. Планка: добивайся максимально кинематографичной, насыщенной и достоверной картинки в реальном времени; конкретные технические приёмы выбираешь сам — оценивается художественное качество и живость, а не следование рецепту.',
    solutions: [
      { model: 'Claude Opus 4.8', slug: 'opus-4.8', dir: 'demos/particle-flow/opus-4.8/' },
      { model: 'GPT-5.5 Codex', slug: 'gpt-5.5-codex', dir: 'demos/particle-flow/gpt-5.5-codex/' },
      { model: 'Claude Fable 5', slug: 'fable-5', dir: 'demos/particle-flow/fable-5/' },
      { model: 'Claude Sonnet 5', slug: 'sonnet-5', dir: 'demos/particle-flow/sonnet-5/' },
      { model: 'GPT-5.6 Sol', slug: 'gpt-5.6-sol', dir: 'demos/particle-flow/gpt-5.6-sol/' },
    ],
  },
  {
    id: 'aurora',
    title: 'Полярное сияние',
    tags: ['атмосфера', 'свет', 'ночь'],
    prompt: 'Полярное сияние над ночным горизонтом на canvas без библиотек: вертикальные ленты-занавеси света, волнообразно колышущиеся, с переливами зелёного, пурпурного и голубого, мягким свечением и вертикальными лучами. Звёздное небо, силуэт ландшафта и отражение сияния. Реальное время, плавная анимация. Планка: добивайся максимально кинематографичной, насыщенной и достоверной картинки в реальном времени; конкретные технические приёмы выбираешь сам — оценивается художественное качество и живость, а не следование рецепту.',
    solutions: [
      { model: 'Claude Opus 4.8', slug: 'opus-4.8', dir: 'demos/aurora/opus-4.8/' },
      { model: 'GPT-5.5 Codex', slug: 'gpt-5.5-codex', dir: 'demos/aurora/gpt-5.5-codex/' },
      { model: 'Claude Fable 5', slug: 'fable-5', dir: 'demos/aurora/fable-5/' },
      { model: 'Claude Sonnet 5', slug: 'sonnet-5', dir: 'demos/aurora/sonnet-5/' },
      { model: 'GPT-5.6 Sol', slug: 'gpt-5.6-sol', dir: 'demos/aurora/gpt-5.6-sol/' },
    ],
  },
  {
    id: 'aquarium',
    title: 'Аквариум с рыбами',
    tags: ['подводный мир', 'анимация', 'атмосфера'],
    prompt: 'Аквариум с рыбами на canvas без библиотек: несколько видов рыб, плавающих с живой естественной анимацией — волнообразный изгиб тела и колебание плавников и хвоста, плавные блуждающие траектории, рыбы разворачиваются у стенок, мелкие держатся стайкой. Подводная среда: каустики света на песчаном дне, нисходящие лучи света сверху, поднимающиеся пузырьки, колышущиеся водоросли, цветовой градиент глубины и лёгкая мутная дымка воды. Реальное время, плавная анимация. Планка: добивайся максимально кинематографичной, насыщенной и достоверной картинки в реальном времени; конкретные технические приёмы выбираешь сам — оценивается художественное качество и живость, а не следование рецепту.',
    solutions: [
      { model: 'Claude Opus 4.8', slug: 'opus-4.8', dir: 'demos/aquarium/opus-4.8/' },
      { model: 'GPT-5.5 Codex', slug: 'gpt-5.5-codex', dir: 'demos/aquarium/gpt-5.5-codex/' },
      { model: 'Claude Fable 5', slug: 'fable-5', dir: 'demos/aquarium/fable-5/' },
      { model: 'Claude Sonnet 5', slug: 'sonnet-5', dir: 'demos/aquarium/sonnet-5/' },
      { model: 'GPT-5.6 Sol', slug: 'gpt-5.6-sol', dir: 'demos/aquarium/gpt-5.6-sol/' },
    ],
  },
  {
    id: 'aquarium-3d',
    title: '3D-аквариум',
    tags: ['подводный мир', '3D', 'атмосфера'],
    prompt: '3D-аквариум с рыбами на canvas без библиотек, с честной 3D-математикой (ручная перспективная проекция, без WebGL): рыбы плавают в настоящем трёхмерном объёме — z-глубина, перспектива, сортировка по дальности (алгоритм художника), масштаб и помутнение/туман с расстоянием. Несколько видов рыб с живой анимацией: волнообразный изгиб тела вдоль хода, колебание плавников и хвоста, рыбы поворачивают корпус по направлению движения (в том числе разворачиваются к камере и от неё с честным укорочением), плавные блуждающие 3D-траектории, развороты у стеклянных стенок объёма, мелкие держатся стайкой. Подводная среда в объёме: песчаное дно с движущимися каустиками, нисходящие объёмные лучи света сверху, поднимающиеся сквозь глубину пузырьки с параллаксом, колышущиеся водоросли на разной дальности, цветовой градиент глубины и мутная дымка воды, мягкие блики на стекле. Медленный облёт/покачивание камеры вокруг аквариума даёт параллакс. Реальное время, плавная анимация. Планка: добивайся максимально кинематографичной, насыщенной и достоверной картинки в реальном времени; конкретные технические приёмы выбираешь сам — оценивается художественное качество и живость, а не следование рецепту.',
    solutions: [
      { model: 'Claude Opus 4.8', slug: 'opus-4.8', dir: 'demos/aquarium-3d/opus-4.8/' },
      { model: 'GPT-5.5 Codex', slug: 'gpt-5.5-codex', dir: 'demos/aquarium-3d/gpt-5.5-codex/' },
      { model: 'Claude Fable 5', slug: 'fable-5', dir: 'demos/aquarium-3d/fable-5/' },
      { model: 'Claude Sonnet 5', slug: 'sonnet-5', dir: 'demos/aquarium-3d/sonnet-5/' },
      { model: 'GPT-5.6 Sol', slug: 'gpt-5.6-sol', dir: 'demos/aquarium-3d/gpt-5.6-sol/' },
    ],
  },

  // ── Настенные часы (ось «достоверность механики + вкус оформления») ──
  {
    id: 'analog-clock',
    title: 'Аналоговые часы',
    tags: ['время', 'анимация', 'canvas'],
    prompt: 'Настенные часы с аналоговым циферблатом на canvas без библиотек: круглый корпус с металлическим ободом и стеклом, чёткие минутные и часовые деления, числа, три стрелки (часовая, минутная, секундная), показывающие реальное системное время и идущие точно. Стрелки отбрасывают мягкие тени, в центре — ось-гайка. Минутная и часовая стрелки движутся непрерывно (часовая учитывает минуты, минутная — секунды), а не скачут по делениям. Секундная — на выбор: плавный «sweep» или механический тик с лёгким отскоком. Циферблат вписан по центру и подстраивается под размер окна, рендер по DPR в реальном времени. Планка: добивайся достоверного, аккуратного и приятного вида настоящих настенных часов; стиль (классика, минимализм, винтаж) и оформление выбираешь сам.',
    solutions: [
      { model: 'Claude Opus 4.8', slug: 'opus-4.8', dir: 'demos/analog-clock/opus-4.8/' },
      { model: 'GPT-5.5 Codex', slug: 'gpt-5.5-codex', dir: 'demos/analog-clock/gpt-5.5-codex/' },
      { model: 'Claude Fable 5', slug: 'fable-5', dir: 'demos/analog-clock/fable-5/' },
      { model: 'Claude Sonnet 5', slug: 'sonnet-5', dir: 'demos/analog-clock/sonnet-5/' },
      { model: 'GPT-5.6 Sol', slug: 'gpt-5.6-sol', dir: 'demos/analog-clock/gpt-5.6-sol/' },
    ],
  },
];
