(()=>{"use strict";
const c=document.getElementById("boidsCanvas"),x=c.getContext("2d",{alpha:false}),N=440,T=Math.PI*2;let W=1,H=1,D=1,chosen=0,last=performance.now(),clock=0,frames=0,seed=0x4c554e41;
const X=new Float32Array(N),Y=new Float32Array(N),VX=new Float32Array(N),VY=new Float32Array(N),S=new Float32Array(N),grid=new Map(),p={sep:1.4,ali:1,coh:.85,rad:92,speed:138};
const el={sep:document.getElementById("sep"),ali:document.getElementById("ali"),coh:document.getElementById("coh"),rad:document.getElementById("rad"),speed:document.getElementById("speed")},out={sep:document.getElementById("sepOut"),ali:document.getElementById("aliOut"),coh:document.getElementById("cohOut"),rad:document.getElementById("radOut"),speed:document.getElementById("speedOut")};
const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296},wrap=(v,n)=>v<0?v+n:v>=n?v-n:v,delta=(a,b,n)=>{let d=a-b;return d>n/2?d-n:d<-n/2?d+n:d};
function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;c.width=W*D;c.height=H*D;x.setTransform(D,0,0,D,0,0);for(let i=0;i<N;i++){X[i]%=W;Y[i]%=H}}
function init(){for(let i=0;i<N;i++){let a=rnd()*T,s=42+rnd()*42;X[i]=rnd()*W;Y[i]=rnd()*H;VX[i]=Math.cos(a)*s;VY[i]=Math.sin(a)*s;S[i]=2.8+rnd()*1.9}}
function sliders(){Object.keys(el).forEach(k=>{p[k]=+el[k].value;let q=(p[k]-+el[k].min)/(+el[k].max-+el[k].min)*100;el[k].style.setProperty("--progress",q+"%");out[k].textContent=k==="rad"||k==="speed"?Math.round(p[k])+(k==="rad"?" px":" px/s"):p[k].toFixed(2)})}
function hash(r){grid.clear();let cols=Math.max(1,Math.ceil(W/r)),rows=Math.max(1,Math.ceil(H/r));for(let i=0;i<N;i++){let a=Math.floor(X[i]/r),b=Math.floor(Y[i]/r),k=b*cols+a,z=grid.get(k);if(!z)grid.set(k,z=[]);z.push(i)}return{cols,rows}}
function nearby(i,r,h,cb){let a=Math.floor(X[i]/r),b=Math.floor(Y[i]/r),rr=r*r;for(let oy=-1;oy<=1;oy++)for(let ox=-1;ox<=1;ox++){let col=(a+ox+h.cols)%h.cols,row=(b+oy+h.rows)%h.rows,z=grid.get(row*h.cols+col);if(!z)continue;for(let q of z){if(q===i)continue;let dx=delta(X[q],X[i],W),dy=delta(Y[q],Y[i],H),d=dx*dx+dy*dy;if(d>0&&d<rr)cb(q,dx,dy,d)}}}
function update(dt){let h=hash(p.rad),sr=Math.min(28,p.rad*.34),s2=sr*sr;for(let i=0;i<N;i++){let ax=0,ay=0,cx=0,cy=0,sx=0,sy=0,n=0;nearby(i,p.rad,h,(j,dx,dy,d)=>{ax+=VX[j];ay+=VY[j];cx+=dx;cy+=dy;if(d<s2){let inv=1/Math.max(d,12);sx-=dx*inv;sy-=dy*inv}n++});let fx=sx*p.sep*900,fy=sy*p.sep*900;if(n){let inv=1/n;fx+=(ax*inv-VX[i])*p.ali*1.8;fy+=(ay*inv-VY[i])*p.ali*1.8;fx+=cx*inv*p.coh*.8;fy+=cy*inv*p.coh*.8}let v=Math.hypot(VX[i],VY[i])||1;VX[i]+=(fx+VX[i]/v*2.2)*dt;VY[i]+=(fy+VY[i]/v*2.2)*dt;v=Math.hypot(VX[i],VY[i]);if(v>p.speed){let z=p.speed/v;VX[i]*=z;VY[i]*=z}else if(v<34){let z=34/Math.max(v,.001);VX[i]*=z;VY[i]*=z}X[i]=wrap(X[i]+VX[i]*dt,W);Y[i]=wrap(Y[i]+VY[i]*dt,H)}}
function background(){let g=x.createRadialGradient(W*.48,H*.43,0,W*.48,H*.43,Math.max(W,H)*.72);g.addColorStop(0,"#171841");g.addColorStop(.5,"#10122f");g.addColorStop(1,"#080a1a");x.fillStyle=g;x.fillRect(0,0,W,H);x.save();x.globalAlpha=.13;x.strokeStyle="#8d8ef0";let step=52,drift=performance.now()*.004%step;for(let a=-step+drift;a<W+step;a+=step){x.beginPath();x.moveTo(a,0);x.lineTo(a,H);x.stroke()}for(let b=-step+drift;b<H+step;b+=step){x.beginPath();x.moveTo(0,b);x.lineTo(W,b);x.stroke()}x.restore()}
function bird(i,sel,near){let a=Math.atan2(VY[i],VX[i]),v=Math.hypot(VX[i],VY[i]),s=S[i],stretch=Math.min(1.6,v/105);x.save();x.translate(X[i],Y[i]);x.rotate(a);x.globalAlpha=sel?1:near?.92:.68;x.fillStyle=sel?"#fff8dc":near?"#73e4e8":"#a8a6ef";x.shadowColor=sel?"#f4c47a":near?"#5ce0e6":"#7571dc";x.shadowBlur=sel?20:near?13:5;x.beginPath();x.moveTo(s*2.5*stretch,0);x.lineTo(-s*1.55,-s*1.35);x.lineTo(-s*.65,0);x.lineTo(-s*1.55,s*1.35);x.closePath();x.fill();x.restore()}
function render(){background();let h=hash(p.rad),list=[];nearby(chosen,p.rad,h,(j,dx,dy)=>list.push({j,dx,dy}));x.save();x.fillStyle="#9e80ff18";x.beginPath();x.arc(X[chosen],Y[chosen],p.rad,0,T);x.fill();x.strokeStyle="#c2afffbb";x.lineWidth=1.7;x.setLineDash([6,6]);x.beginPath();x.arc(X[chosen],Y[chosen],p.rad,0,T);x.stroke();x.setLineDash([]);x.strokeStyle="#75e3e88c";x.lineWidth=1;for(let q of list){x.beginPath();x.moveTo(X[chosen],Y[chosen]);x.lineTo(X[chosen]+q.dx,Y[chosen]+q.dy);x.stroke()}x.strokeStyle="#ffecb9cc";x.lineWidth=1.5;x.beginPath();x.arc(X[chosen],Y[chosen],11,0,T);x.stroke();x.fillStyle="#f7d894";x.font="600 10px system-ui";x.fillText(list.length+" СОСЕДЕЙ",X[chosen]+17,Y[chosen]-14);x.restore();let set=new Set(list.map(q=>q.j));for(let i=0;i<N;i++)bird(i,i===chosen,set.has(i));x.globalAlpha=.28;x.fillStyle="#a99dff";x.font="10px system-ui";x.fillText("TOROIDAL FIELD  /  CLICK TO SELECT",22,H-22)}
function tick(now){let dt=Math.min((now-last)/1000,.033);last=now;update(dt);render();clock+=dt;frames++;if(clock>.45){document.getElementById("fps").textContent=Math.min(60,Math.round(frames/clock));clock=0;frames=0}requestAnimationFrame(tick)}
c.addEventListener("pointerdown",e=>{let r=c.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,best=Infinity;for(let i=0;i<N;i++){let dx=delta(X[i],mx,W),dy=delta(Y[i],my,H),d=dx*dx+dy*dy;if(d<best){best=d;chosen=i}}});
Object.keys(el).forEach(k=>el[k].addEventListener("input",sliders));document.getElementById("reset").addEventListener("click",()=>{Object.keys(p).forEach(k=>el[k].value=p[k]);sliders()});addEventListener("resize",resize);resize();init();sliders();requestAnimationFrame(tick)
})()