(()=>{"use strict";
const canvas=document.getElementById("scene"),ctx=canvas.getContext("2d",{alpha:true});
const $=id=>document.getElementById(id),ui={toggle:$("toggleButton"),toggleIcon:$("toggleIcon"),toggleLabel:$("toggleLabel"),reset:$("resetButton"),ghost:$("ghostToggle"),ghostLegend:$("ghostLegend"),time:$("timeValue"),divergence:$("divergenceValue"),energy:$("energyValue"),m1:$("m1"),m2:$("m2"),l1:$("l1"),l2:$("l2"),m1Out:$("m1Out"),m2Out:$("m2Out"),l1Out:$("l1Out"),l2Out:$("l2Out")};
const G=9.81,STEP=1/240,MAX_DT=.05,GHOST_OFFSET=Math.PI/3600,TRAIL_LIFE=7.5;
const p={m1:1,m2:1.2,l1:1,l2:1};let W=0,H=0,dpr=1,running=true,acc=0,last=performance.now(),time=0,sample=0,state,ghost,trail=[],ghostTrail=[],e0=0;
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
// Полная нелинейная форма уравнений Эйлера — Лагранжа, углы отсчитываются от вертикали.
function deriv(s){const[a,w,b,v]=s,d=a-b,sd=Math.sin(d),cd=Math.cos(d),q=2*p.m1+p.m2-p.m2*Math.cos(2*d);const aa=(-G*(2*p.m1+p.m2)*Math.sin(a)-p.m2*G*Math.sin(a-2*b)-2*p.m2*sd*(v*v*p.l2+w*w*p.l1*cd))/(p.l1*q);const ab=2*sd*(w*w*p.l1*(p.m1+p.m2)+G*(p.m1+p.m2)*Math.cos(a)+v*v*p.l2*p.m2*cd)/(p.l2*q);return[w,aa,v,ab]}
function rk4(s,h){const k1=deriv(s),k2=deriv(s.map((x,i)=>x+k1[i]*h/2)),k3=deriv(s.map((x,i)=>x+k2[i]*h/2)),k4=deriv(s.map((x,i)=>x+k3[i]*h));return s.map((x,i)=>x+h*(k1[i]+2*k2[i]+2*k3[i]+k4[i])/6)}
function pos(s){return{x1:p.l1*Math.sin(s[0]),y1:p.l1*Math.cos(s[0]),x2:p.l1*Math.sin(s[0])+p.l2*Math.sin(s[2]),y2:p.l1*Math.cos(s[0])+p.l2*Math.cos(s[2])}}
function energy(s){const[a,w,b,v]=s;return .5*(p.m1+p.m2)*p.l1*p.l1*w*w+.5*p.m2*p.l2*p.l2*v*v+p.m2*p.l1*p.l2*w*v*Math.cos(a-b)-(p.m1+p.m2)*G*p.l1*Math.cos(a)-p.m2*G*p.l2*Math.cos(b)}
function addTrail(){const a=pos(state);trail.push({x:a.x2,y:a.y2,t:time});if(ui.ghost.checked){const b=pos(ghost);ghostTrail.push({x:b.x2,y:b.y2,t:time})}const cut=time-TRAIL_LIFE;while(trail.length&&trail[0].t<cut)trail.shift();while(ghostTrail.length&&ghostTrail[0].t<cut)ghostTrail.shift()}
function reset(){state=[2.18,0,1.32,0];ghost=[state[0]+GHOST_OFFSET,0,state[2],0];time=acc=sample=0;trail=[];ghostTrail=[];e0=energy(state);addTrail();metrics()}
function tick(){state=rk4(state,STEP);ghost=rk4(ghost,STEP);time+=STEP;if(++sample>=4){sample=0;addTrail()}}
function view(){const mobile=W<650,allow=mobile?245:W<1000?225:195,usable=Math.max(250,H-allow);return{x:mobile?W*.56:W*.61,y:mobile?Math.min(205,H*.31):Math.max(122,H*.22),scale:Math.min(W*(mobile?.36:.31),usable*.68)/(p.l1+p.l2)}}
function screen(s,v){const q=pos(s);return{x1:v.x+q.x1*v.scale,y1:v.y+q.y1*v.scale,x2:v.x+q.x2*v.scale,y2:v.y+q.y2*v.scale}}
function backdrop(v){ctx.clearRect(0,0,W,H);const g=ctx.createRadialGradient(v.x,v.y+100,0,v.x,v.y+100,Math.min(W,H)*.5);g.addColorStop(0,"rgba(94,69,135,.12)");g.addColorStop(.48,"rgba(35,46,72,.045)");g.addColorStop(1,"rgba(0,0,0,0)");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.save();ctx.strokeStyle="rgba(255,255,255,.025)";for(let x=((v.x%48)+48)%48;x<W;x+=48){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=((v.y%48)+48)%48;y<H;y+=48){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.restore()}
function drawTrail(a,v,color,strength){if(a.length<2)return;ctx.save();ctx.lineCap="round";ctx.lineJoin="round";ctx.globalCompositeOperation="lighter";for(let i=1;i<a.length;i++){const life=Math.max(0,1-(time-a[i].t)/TRAIL_LIFE),alpha=life*life*strength;if(alpha<.004)continue;ctx.beginPath();ctx.moveTo(v.x+a[i-1].x*v.scale,v.y+a[i-1].y*v.scale);ctx.lineTo(v.x+a[i].x*v.scale,v.y+a[i].y*v.scale);ctx.strokeStyle=`rgba(${color},${alpha})`;ctx.lineWidth=.7+2.2*life;ctx.shadowColor=`rgba(${color},${Math.min(alpha*1.8,.5)})`;ctx.shadowBlur=7*life;ctx.stroke()}ctx.restore()}
function mass(x,y,r,color,alpha){ctx.save();ctx.globalAlpha=alpha;ctx.shadowColor=color;ctx.shadowBlur=r*1.9;const g=ctx.createRadialGradient(x-r*.28,y-r*.3,1,x,y,r);g.addColorStop(0,"rgba(255,255,255,.96)");g.addColorStop(.22,color);g.addColorStop(1,color==="#ff647c"?"#b52852":color==="#ffb454"?"#b66a31":"#198ba5");ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle="rgba(255,255,255,.42)";ctx.stroke();ctx.restore()}
function pendulum(s,v,isGhost){const q=screen(s,v),rod=isGhost?"rgba(98,230,255,.42)":"rgba(225,228,237,.78)",joint=isGhost?"#62e6ff":"#ffb454",load=isGhost?"#62e6ff":"#ff647c";ctx.save();if(isGhost)ctx.setLineDash([5,6]);ctx.lineCap="round";ctx.lineWidth=isGhost?1.35:2.2;ctx.strokeStyle=rod;ctx.shadowColor=isGhost?"rgba(98,230,255,.2)":"rgba(255,255,255,.12)";ctx.shadowBlur=8;ctx.beginPath();ctx.moveTo(v.x,v.y);ctx.lineTo(q.x1,q.y1);ctx.lineTo(q.x2,q.y2);ctx.stroke();ctx.setLineDash([]);mass(q.x1,q.y1,7+Math.sqrt(p.m1)*3.2,joint,isGhost?.48:1);mass(q.x2,q.y2,8+Math.sqrt(p.m2)*3.6,load,isGhost?.58:1);ctx.restore()}
function pivot(v){ctx.save();ctx.strokeStyle="rgba(255,255,255,.12)";ctx.beginPath();ctx.arc(v.x,v.y,18,0,Math.PI*2);ctx.stroke();ctx.fillStyle="#e8ebf2";ctx.shadowColor="white";ctx.shadowBlur=13;ctx.beginPath();ctx.arc(v.x,v.y,4.2,0,Math.PI*2);ctx.fill();ctx.restore()}
function render(){const v=view();backdrop(v);drawTrail(trail,v,"255,100,124",.62);if(ui.ghost.checked){drawTrail(ghostTrail,v,"98,230,255",.48);pendulum(ghost,v,true)}pendulum(state,v,false);pivot(v)}
function metrics(){const a=pos(state),b=pos(ghost),d=Math.hypot(a.x2-b.x2,a.y2-b.y2)/(p.l1+p.l2),drift=Math.abs(e0)>1e-9?Math.abs((energy(state)-e0)/e0)*100:0;ui.time.textContent=`${time.toFixed(1).replace(".",",")} с`;ui.divergence.textContent=ui.ghost.checked?d.toFixed(3).replace(".",","):"—";ui.energy.textContent=`${drift.toFixed(drift<.01?3:2).replace(".",",")}%`}
function frame(now){const dt=Math.min((now-last)/1000,MAX_DT);last=now;if(running){acc+=dt;while(acc>=STEP){tick();acc-=STEP}}metrics();render();requestAnimationFrame(frame)}
function setRunning(x){running=x;ui.toggleIcon.textContent=x?"Ⅱ":"▶";ui.toggleLabel.textContent=x?"Пауза":"Пуск";ui.toggle.setAttribute("aria-label",x?"Поставить симуляцию на паузу":"Запустить симуляцию");last=performance.now()}
function range(input,out,unit){const x=+input.value;out.textContent=`${x.toFixed(2).replace(/0$/,"").replace(".",",")} ${unit}`;input.style.setProperty("--fill",`${(x-input.min)/(input.max-input.min)*100}%`);return x}
function sync(changed){p.m1=range(ui.m1,ui.m1Out,"кг");p.m2=range(ui.m2,ui.m2Out,"кг");p.l1=range(ui.l1,ui.l1Out,"м");p.l2=range(ui.l2,ui.l2Out,"м");if(changed){trail=[];ghostTrail=[];e0=energy(state);addTrail()}}
ui.toggle.addEventListener("click",()=>setRunning(!running));ui.reset.addEventListener("click",reset);ui.ghost.addEventListener("change",()=>{ui.ghostLegend.classList.toggle("disabled",!ui.ghost.checked);if(ui.ghost.checked&&!ghostTrail.length){const q=pos(ghost);ghostTrail.push({x:q.x2,y:q.y2,t:time})}});[ui.m1,ui.m2,ui.l1,ui.l2].forEach(x=>x.addEventListener("input",()=>sync(true)));addEventListener("keydown",e=>{if(e.target instanceof HTMLInputElement)return;if(e.code==="Space"){e.preventDefault();setRunning(!running)}else if(e.key.toLowerCase()==="r")reset();else if(e.key.toLowerCase()==="g"){ui.ghost.checked=!ui.ghost.checked;ui.ghost.dispatchEvent(new Event("change"))}});addEventListener("resize",resize,{passive:true});resize();sync(false);reset();requestAnimationFrame(frame)})();