(()=>{'use strict';
const canvas=document.getElementById('scene'),ctx=canvas.getContext('2d',{alpha:false}),debugToggle=document.getElementById('debugToggle'),rayCount=document.getElementById('rayCount'),dprValue=document.getElementById('dprValue'),TAU=Math.PI*2,EPSILON=.00018;
const state={width:0,height:0,dpr:1,light:{x:0,y:0},target:{x:0,y:0},pointerInside:false,elapsed:0,lastTime:performance.now(),obstacles:[],visibility:[]};
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v)),cross=(a,b)=>a.x*b.y-a.y*b.x,sub=(a,b)=>({x:a.x-b.x,y:a.y-b.y});
function resize(){state.width=innerWidth;state.height=innerHeight;state.dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(state.width*state.dpr);canvas.height=Math.round(state.height*state.dpr);ctx.setTransform(state.dpr,0,0,state.dpr,0,0);if(!state.light.x){state.light.x=state.target.x=state.width*.5;state.light.y=state.target.y=state.height*.48}else{state.light.x=clamp(state.light.x,20,state.width-20);state.light.y=clamp(state.light.y,20,state.height-20)}createObstacles();dprValue.textContent=state.dpr.toFixed(1)}
function createObstacles(){const w=state.width,h=state.height,p=a=>a.map(([x,y])=>({x:x*w,y:y*h}));state.obstacles=[p([[.12,.19],[.27,.14],[.32,.27],[.22,.36],[.11,.31]]),p([[.41,.16],[.55,.11],[.62,.22],[.57,.34],[.44,.31]]),p([[.75,.16],[.91,.22],[.87,.36],[.72,.34],[.69,.24]]),p([[.27,.52],[.41,.44],[.50,.53],[.47,.69],[.31,.70],[.24,.61]]),p([[.64,.48],[.77,.44],[.85,.55],[.79,.68],[.65,.66],[.59,.56]]),p([[.10,.75],[.23,.70],[.31,.82],[.24,.93],[.09,.89]]),p([[.43,.79],[.55,.74],[.64,.82],[.60,.95],[.45,.92]])];rayCount.textContent=String(state.obstacles.reduce((sum,poly)=>sum+poly.length,0)*3)}
function raySegment(origin,direction,a,b){const edge=sub(b,a),den=cross(direction,edge);if(Math.abs(den)<1e-9)return null;const from=sub(a,origin),distance=cross(from,edge)/den,position=cross(from,direction)/den;return distance>=0&&position>=-1e-8&&position<=1+1e-8?distance:null}
function castRay(angle){const d={x:Math.cos(angle),y:Math.sin(angle)};let nearest=Math.hypot(state.width,state.height)*1.5;for(const poly of state.obstacles)for(let i=0;i<poly.length;i++){const hit=raySegment(state.light,d,poly[i],poly[(i+1)%poly.length]);if(hit!==null&&hit<nearest)nearest=hit}return{x:state.light.x+d.x*nearest,y:state.light.y+d.y*nearest,angle}}
function calculateVisibility(){const angles=[];for(const poly of state.obstacles)for(const v of poly){const a=Math.atan2(v.y-state.light.y,v.x-state.light.x);angles.push(a-EPSILON,a,a+EPSILON)}angles.sort((a,b)=>a-b);state.visibility=angles.map(castRay)}
function drawBackground(){const g=ctx.createLinearGradient(0,0,state.width,state.height);g.addColorStop(0,'#0d1729');g.addColorStop(.48,'#0a1221');g.addColorStop(1,'#080c16');ctx.fillStyle=g;ctx.fillRect(0,0,state.width,state.height);ctx.save();ctx.globalAlpha=.13;ctx.strokeStyle='#72839c';const grid=52;for(let x=0;x<state.width;x+=grid){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,state.height);ctx.stroke()}for(let y=0;y<state.height;y+=grid){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(state.width,y);ctx.stroke()}ctx.restore();ctx.save();ctx.globalAlpha=.4;ctx.fillStyle='#d8c399';for(let i=0;i<55;i++){const x=i*137.3%state.width,y=(i*71.7+23)%state.height,s=i%7===0?1.4:.6;ctx.beginPath();ctx.arc(x,y,s,0,TAU);ctx.fill()}ctx.restore()}
function path(poly){ctx.beginPath();ctx.moveTo(poly[0].x,poly[0].y);for(let i=1;i<poly.length;i++)ctx.lineTo(poly[i].x,poly[i].y);ctx.closePath()}
function drawObstacles(){for(const poly of state.obstacles){path(poly);ctx.fillStyle='rgba(8,12,22,.94)';ctx.fill();ctx.strokeStyle='rgba(162,171,191,.24)';ctx.lineWidth=1.2;ctx.stroke();ctx.save();ctx.clip();const g=ctx.createLinearGradient(0,0,state.width,state.height);g.addColorStop(0,'rgba(111,129,157,.14)');g.addColorStop(.4,'rgba(54,70,94,.04)');g.addColorStop(1,'rgba(0,0,0,.2)');ctx.fillStyle=g;ctx.fillRect(0,0,state.width,state.height);ctx.restore()}}
function drawLight(){if(!state.visibility.length)return;ctx.save();ctx.beginPath();ctx.moveTo(state.visibility[0].x,state.visibility[0].y);for(let i=1;i<state.visibility.length;i++)ctx.lineTo(state.visibility[i].x,state.visibility[i].y);ctx.closePath();ctx.clip();const pulse=1+Math.sin(state.elapsed*2.4)*.035,radius=Math.max(state.width,state.height)*.64*pulse,g=ctx.createRadialGradient(state.light.x,state.light.y,0,state.light.x,state.light.y,radius);g.addColorStop(0,'rgba(255,250,219,.96)');g.addColorStop(.045,'rgba(255,226,157,.78)');g.addColorStop(.18,'rgba(255,196,107,.30)');g.addColorStop(.52,'rgba(240,155,80,.10)');g.addColorStop(1,'rgba(220,126,66,0)');ctx.fillStyle=g;ctx.fillRect(0,0,state.width,state.height);ctx.restore();ctx.save();ctx.globalCompositeOperation='lighter';const r=58+Math.sin(state.elapsed*2.4)*4,g2=ctx.createRadialGradient(state.light.x,state.light.y,0,state.light.x,state.light.y,r);g2.addColorStop(0,'rgba(255,250,219,.98)');g2.addColorStop(.12,'rgba(255,224,153,.72)');g2.addColorStop(.42,'rgba(255,181,92,.22)');g2.addColorStop(1,'rgba(247,156,73,0)');ctx.fillStyle=g2;ctx.beginPath();ctx.arc(state.light.x,state.light.y,r,0,TAU);ctx.fill();ctx.restore();ctx.fillStyle='#fff6d5';ctx.beginPath();ctx.arc(state.light.x,state.light.y,3.2,0,TAU);ctx.fill()}
function drawDebug(){if(!debugToggle.checked)return;ctx.save();ctx.lineWidth=1;ctx.strokeStyle='rgba(255,213,139,.22)';ctx.fillStyle='#ffd38b';for(const point of state.visibility){ctx.beginPath();ctx.moveTo(state.light.x,state.light.y);ctx.lineTo(point.x,point.y);ctx.stroke()}for(const poly of state.obstacles)for(const v of poly){ctx.beginPath();ctx.arc(v.x,v.y,3,0,TAU);ctx.fill();ctx.beginPath();ctx.arc(v.x,v.y,6,0,TAU);ctx.stroke()}ctx.strokeStyle='rgba(255,245,217,.85)';ctx.beginPath();ctx.arc(state.light.x,state.light.y,9,0,TAU);ctx.stroke();ctx.restore()}
function render(now){const dt=clamp((now-state.lastTime)/1000,0,.05);state.lastTime=now;state.elapsed+=dt;const follow=1-Math.pow(.0008,dt);state.light.x+=(state.target.x-state.light.x)*follow;state.light.y+=(state.target.y-state.light.y)*follow;if(!state.pointerInside){state.target.x=state.width*(.5+Math.cos(state.elapsed*.23)*.06);state.target.y=state.height*(.48+Math.sin(state.elapsed*.31)*.07)}calculateVisibility();drawBackground();drawLight();drawObstacles();drawDebug();requestAnimationFrame(render)}
function updatePointer(event){state.target.x=event.clientX;state.target.y=event.clientY;state.pointerInside=true}
canvas.addEventListener('pointermove',updatePointer,{passive:true});canvas.addEventListener('pointerleave',()=>{state.pointerInside=false},{passive:true});addEventListener('resize',resize,{passive:true});resize();requestAnimationFrame(render);
})();
