(() => {
  "use strict";
  const canvas=document.getElementById("terrain-canvas"),ctx=canvas.getContext("2d",{alpha:false});
  const heightRange=document.getElementById("height-range"),distanceRange=document.getElementById("distance-range"),horizonRange=document.getElementById("horizon-range");
  const heightOutput=document.getElementById("height-output"),distanceOutput=document.getElementById("distance-output"),horizonOutput=document.getElementById("horizon-output");
  const pauseButton=document.getElementById("pause-button"),fpsValue=document.getElementById("fps-value"),altitudeValue=document.getElementById("altitude-value"),sectorValue=document.getElementById("sector-value");
  const MAP_SIZE=512,TERRAIN_SCALE=56,FOG_COLOR=[25,37,59],heightMap=new Float32Array(MAP_SIZE*MAP_SIZE);
  const state={width:0,height:0,dpr:1,cameraHeight:42,drawDistance:320,horizon:48,x:86.4,y:242.8,angle:.18,speed:18,time:0,paused:false,lastFrame:0,fpsTimer:0,frames:0,drag:false,lastPointerX:0};
  const clamp=(v,min,max)=>Math.max(min,Math.min(max,v)),wrap=(v,size)=>((v%size)+size)%size,lerp=(a,b,t)=>a+(b-a)*t,smooth=t=>t*t*(3-2*t);
  function hash(x,y){const n=Math.sin(x*127.1+y*311.7)*43758.5453123;return n-Math.floor(n);}
  function valueNoise(x,y){const ix=Math.floor(x),iy=Math.floor(y),fx=smooth(x-ix),fy=smooth(y-iy),a=hash(ix,iy),b=hash(ix+1,iy),c=hash(ix,iy+1),d=hash(ix+1,iy+1);return lerp(lerp(a,b,fx),lerp(c,d,fx),fy);}
  function fbm(x,y){let value=0,amplitude=.5,frequency=1;for(let octave=0;octave<5;octave+=1){value+=valueNoise(x*frequency,y*frequency)*amplitude;frequency*=2.03;amplitude*=.5;}return value;}
  function buildHeightMap(){for(let y=0;y<MAP_SIZE;y+=1){for(let x=0;x<MAP_SIZE;x+=1){const nx=x/MAP_SIZE,ny=y/MAP_SIZE,large=fbm(nx*5.2+4.1,ny*5.2-1.7),detail=fbm(nx*19-8.3,ny*19+2.2),ridges=1-Math.abs(large*2-1);let height=large*.58+detail*.19+ridges*.23;const basin=Math.hypot(nx-.48,ny-.56);height-=clamp((basin-.34)*.16,0,.08);heightMap[y*MAP_SIZE+x]=clamp(Math.pow(height,1.08),0,1);}}}
  function sampleHeight(x,y){return heightMap[wrap(Math.floor(y),MAP_SIZE)*MAP_SIZE+wrap(Math.floor(x),MAP_SIZE)];}
  function terrainColor(height,slope,fog){let r,g,b;if(height<.22){const t=height/.22;r=lerp(9,17,t);g=lerp(24,53,t);b=lerp(43,70,t);}else if(height<.43){const t=(height-.22)/.21;r=lerp(17,38,t);g=lerp(53,93,t);b=lerp(70,92,t);}else if(height<.66){const t=(height-.43)/.23;r=lerp(38,112,t);g=lerp(93,118,t);b=lerp(92,103,t);}else if(height<.84){const t=(height-.66)/.18;r=lerp(112,179,t);g=lerp(118,133,t);b=lerp(103,111,t);}else{const t=(height-.84)/.16;r=lerp(179,235,t);g=lerp(133,216,t);b=lerp(111,180,t);}const light=clamp((.45-slope)*.32,-.12,.14);r=clamp(r*(1+light),0,255);g=clamp(g*(1+light),0,255);b=clamp(b*(1+light),0,255);return `rgb(${Math.round(lerp(r,FOG_COLOR[0],fog))},${Math.round(lerp(g,FOG_COLOR[1],fog))},${Math.round(lerp(b,FOG_COLOR[2],fog))})`;}
  function resize(){state.width=innerWidth;state.height=innerHeight;state.dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.floor(state.width*state.dpr));canvas.height=Math.max(1,Math.floor(state.height*state.dpr));ctx.setTransform(state.dpr,0,0,state.dpr,0,0);}
  function drawSky(horizonY){const sky=ctx.createLinearGradient(0,0,0,horizonY+state.height*.16);sky.addColorStop(0,"#081422");sky.addColorStop(.52,"#172a43");sky.addColorStop(1,"#48637d");ctx.fillStyle=sky;ctx.fillRect(0,0,state.width,state.height);const haze=ctx.createRadialGradient(state.width*.62,horizonY,0,state.width*.62,horizonY,state.width*.7);haze.addColorStop(0,"rgba(176,194,195,.2)");haze.addColorStop(1,"rgba(176,194,195,0)");ctx.fillStyle=haze;ctx.fillRect(0,0,state.width,horizonY+80);ctx.save();ctx.globalAlpha=.72;ctx.fillStyle="#e6e1c7";ctx.beginPath();ctx.arc(state.width*.78,Math.max(74,horizonY*.42),23,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.18;ctx.fillStyle="#d4ebff";ctx.beginPath();ctx.arc(state.width*.78-9,Math.max(74,horizonY*.42)-7,30,0,Math.PI*2);ctx.fill();ctx.restore();}
  function render(){const horizonY=state.height*(state.horizon/100)+Math.sin(state.time*.55)*1.2;drawSky(horizonY);const focal=Math.max(180,state.height*.92),columnStep=2,near=3,far=state.drawDistance,depthStep=Math.max(2.5,far/100),columnWidth=2.6;ctx.save();ctx.beginPath();ctx.rect(0,horizonY-2,state.width,state.height-horizonY+2);ctx.clip();for(let screenX=0;screenX<state.width;screenX+=columnStep){const rayAngle=state.angle+Math.atan((screenX-state.width*.5)/focal),rayX=Math.cos(rayAngle),rayY=Math.sin(rayAngle);let maxY=state.height+4;for(let depth=far;depth>=near;depth-=depthStep){const terrainX=state.x+rayX*depth,terrainY=state.y+rayY*depth,height=sampleHeight(terrainX,terrainY),projectedY=horizonY+(state.cameraHeight-height*TERRAIN_SCALE)*focal/Math.max(depth,1);if(projectedY>=maxY||projectedY>state.height+8)continue;const ahead=sampleHeight(terrainX+rayX*1.5,terrainY+rayY*1.5),side=sampleHeight(terrainX+rayY*1.5,terrainY-rayX*1.5),slope=Math.abs(height-(ahead+side)*.5),fog=clamp((depth/far)*(depth/far)*.84,0,.92);ctx.fillStyle=terrainColor(height,slope,fog);ctx.fillRect(screenX,projectedY,columnWidth,maxY-projectedY+1);maxY=projectedY;}}ctx.restore();const bottomFade=ctx.createLinearGradient(0,state.height*.76,0,state.height);bottomFade.addColorStop(0,"rgba(4,9,19,0)");bottomFade.addColorStop(1,"rgba(4,9,19,.22)");ctx.fillStyle=bottomFade;ctx.fillRect(0,state.height*.72,state.width,state.height*.28);ctx.save();ctx.globalAlpha=.1;ctx.strokeStyle="#c8e4e0";ctx.beginPath();ctx.moveTo(18,horizonY);ctx.lineTo(76,horizonY);ctx.moveTo(state.width-76,horizonY);ctx.lineTo(state.width-18,horizonY);ctx.stroke();ctx.restore();}
  function updateLabels(){heightOutput.value=`${state.cameraHeight} m`;distanceOutput.value=`${state.drawDistance} u`;horizonOutput.value=`${state.horizon}%`;altitudeValue.textContent=`${String(state.cameraHeight).padStart(3,"0")}.0 m`;const sectorX=Math.floor(wrap(state.x,MAP_SIZE)/32).toString().padStart(2,"0"),sectorY=Math.floor(wrap(state.y,MAP_SIZE)/32).toString().padStart(2,"0");sectorValue.textContent=`L-${sectorX} / ${sectorY}`;[heightRange,distanceRange,horizonRange].forEach(input=>{const percent=((input.value-input.min)/(input.max-input.min))*100;input.style.setProperty("--fill",`${percent}%`);});}
  function animate(timestamp){if(!state.lastFrame)state.lastFrame=timestamp;const dt=Math.min((timestamp-state.lastFrame)/1000,.05);state.lastFrame=timestamp;if(!state.paused){state.time+=dt;state.x=wrap(state.x+Math.cos(state.angle)*state.speed*dt,MAP_SIZE);state.y=wrap(state.y+Math.sin(state.angle)*state.speed*dt,MAP_SIZE);render();}state.frames+=1;state.fpsTimer+=dt;if(state.fpsTimer>=.5){fpsValue.textContent=String(Math.round(state.frames/state.fpsTimer)).padStart(2,"0");state.fpsTimer=0;state.frames=0;updateLabels();}requestAnimationFrame(animate);}
  function setPaused(value){state.paused=value;pauseButton.classList.toggle("is-paused",value);pauseButton.setAttribute("aria-pressed",String(value));pauseButton.setAttribute("aria-label",value?"Продолжить полёт":"Поставить полёт на паузу");}
  heightRange.addEventListener("input",()=>{state.cameraHeight=Number(heightRange.value);updateLabels();});distanceRange.addEventListener("input",()=>{state.drawDistance=Number(distanceRange.value);updateLabels();});horizonRange.addEventListener("input",()=>{state.horizon=Number(horizonRange.value);updateLabels();});pauseButton.addEventListener("click",()=>setPaused(!state.paused));
  canvas.addEventListener("pointerdown",event=>{state.drag=true;state.lastPointerX=event.clientX;canvas.classList.add("is-dragging");canvas.setPointerCapture(event.pointerId);});canvas.addEventListener("pointermove",event=>{if(!state.drag)return;state.angle+=(event.clientX-state.lastPointerX)*.004;state.lastPointerX=event.clientX;});const endDrag=event=>{state.drag=false;canvas.classList.remove("is-dragging");if(event&&canvas.hasPointerCapture(event.pointerId))canvas.releasePointerCapture(event.pointerId);};canvas.addEventListener("pointerup",endDrag);canvas.addEventListener("pointercancel",endDrag);addEventListener("resize",resize);
  buildHeightMap();resize();updateLabels();render();requestAnimationFrame(animate);
})();
